name: Ejecutar Pruebas con Docker Compose

on:
  push:
    branches: [ "master" ]

jobs:
  test-with-compose:
    name: Probar con Docker Compose
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Cachear repositorio de Maven
        uses: actions/cache@v3
        with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-

      - name: Instalar Docker Compose
        run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

      - name: Construir la imagen de la app
        run: docker-compose build app

      - name: Ejecutar pruebas con docker-compose run
        run: docker-compose run --rm app mvn -B test
